package at.gameserver.minigame;

public enum Message {
	
	PLAYER_JOIN_PUBLIC, PLAYER_JOIN_SINGLE, PLAYER_LEAVE_PUBLIC, PLAYER_LEAVE_SINGLE, COUNTDOWN_START, COUNTDOWN_CANCEL, GAME_START, GAME_FINISH
}
